# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180906_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Team'),
            preserve_default=False,
        ),
    ]
