# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180906_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date_captured',
        ),
    ]
