# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180907_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Session'),
            preserve_default=False,
        ),
    ]
