# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_report_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='session',
        ),
    ]
