# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 13:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_detainee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text_data',
            field=tinymce.models.HTMLField(),
        ),
    ]
